- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile: bash/bash_profile
    ~/.bashrc: bash/bashrc
    ~/.dotfiles: ''
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.shell:
    ~/.zsh:
    ~/.zshrc: zsh/zshrc
    ~/.antigenrc: zsh/antigenrc

- shell:
  -
    command: git submodule update --force --recursive # after linking ~/.gitconfig
    stdout: true
