#!/usr/bin/env bash

set -euo pipefail

if [ -z "$HOME" ];
then
    echo "Seems you're \$HOMEless :(";
    exit 1;
fi

if command -v stow >/dev/null ; then
    # noop
    echo >/dev/null
else
    echo "please install stow, probably with brew"
    exit 1
fi

git submodule update --init --force --recursive --remote

CONFIG=".install.conf.yaml"
DOTBOT_DIR="dotbot/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
--plugin-dir dotbot/plugins/dotbot-pip \
--plugin-dir dotbot/plugins/dotbot-brew \
-c "${CONFIG}" ${@+"$@"}

chmod +x homebrew/brew.sh && ./homebrew/brew.sh

if [[ "$(uname -s)" == "Darwin" ]];
then
    chmod +x macos/install.sh && ./macos/install.sh
elif [[ "$( uname )" == "Linux" ]];
then
    chmod +x linux/install.sh && ./linux/install.sh
fi

zsh_path="$( which zsh )"
if ! grep "$zsh_path" /etc/shells;
then
    echo "adding $zsh_path to /etc/shells"
    echo "$zsh_path" | sudo tee -a /etc/shells
fi
if [[ "$SHELL" != "$zsh_path" ]];
then
    chsh -s "$zsh_path"
    echo "default shell changed to $zsh_path"
fi

echo -e "\\nDone."
