if [[ "$( uname )" == "Darwin" ]];
then
    export PATH=/usr/local/bin:$PATH
    source /usr/local/share/antigen/antigen.zsh
elif [[ "$( uname )" == "Linux" ]];
then
    export PATH=$HOME/.local/bin:$PATH
    export PATH=$HOME/.linuxbrew/bin:$PATH
    export MANPATH=$HOME/.linuxbrew/share/man:$MANPATH
    export INFOPATH=$HOME/.linuxbrew/share/info:$INFOPATH
    source $HOME/.linuxbrew/share/antigen/antigen.zsh
fi

antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle command-not-found
antigen bundle pip

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship
source ~/.zsh/spaceship.zsh

antigen apply

# Aliases
source ~/.shell/aliases.sh

# Secrets
source ~/.shell/secrets.sh

# External
source ~/.shell/external.sh

# OS-specific
if [[ "$(uname)" == "Darwin" ]];
then
    antigen bundle osx
    source ~/.shell/macOS.sh
elif [[ "$(uname)" == "Linux" ]];
then
    # None so far...
fi
