source $HOME/.dotfiles/zsh/antigen/bin/antigen.zsh

# Aliases
source ~/.shell/aliases.sh

# Secrets
source ~/.shell/secrets.sh

# External
source ~/.shell/external.sh

# OS-specific
if [[ "$( uname )" == "Darwin" ]];
then
    source ~/.shell/macOS.sh
elif [[ "$( uname )" == "Linux" ]];
then
    # None so far...
fi

antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle command-not-found
antigen bundle pip

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

antigen theme awesomepanda
# antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship
# source ~/.shell/spaceship.zsh

antigen apply
