#!/usr/bin/env bash

set -euo pipefail

if [ -z "${HOME:-}" ];
then
    echo "Seems you're \$HOMEless :("
    exit 1
fi

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${BASEDIR}"

if [[ "${SKIP_BREW:-0}" != "1" ]];
then
    chmod +x homebrew/brew.sh && ./homebrew/brew.sh
fi

if [[ "$(uname -s)" == "Darwin" ]];
then
    chmod +x macOS/install.sh && ./macOS/install.sh
elif [[ "$( uname )" == "Linux" ]];
then
    chmod +x linux/install.sh && ./linux/install.sh
fi

zsh_path="$(command -v zsh)"
if ! grep -qxF "$zsh_path" /etc/shells;
then
    echo "adding $zsh_path to /etc/shells"
    echo "$zsh_path" | sudo tee -a /etc/shells
fi
if [[ "$SHELL" != "$zsh_path" ]];
then
    chsh -s "$zsh_path"
    echo "default shell changed to $zsh_path"
fi

echo -e "\\nDone."
