if [[ "$( uname )" == "Darwin" ]];
then
    export PATH=/usr/local/bin:$PATH
elif [[ "$( uname )" == "Linux" ]];
then
    test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
    test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
    test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"'
    echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"'
    export PATH=$HOME/.local/bin:$PATH
    export PATH=$HOME/.linuxbrew/bin:$PATH
    export PATH=/home/linuxbrew/.linuxbrewbin:$PATH
    export MANPATH=/home/linuxbrew/.linuxbrewshare/man:$MANPATH
    export INFOPATH=/home/linuxbrew/.linuxbrewshare/info:$INFOPATH
fi

# Aliases
source ~/.shell/aliases.sh

# Secrets file
source ~/.shell/secrets.sh

# External settings
source ~/.shell/external.sh

# OS-specific
if [[ "$( uname )" == "Darwin" ]];
then
    source ~/.shell/macOS.sh
fi
