if [[ "$( uname )" == "Darwin" ]];
then
    export PATH=/usr/local/bin:$PATH
elif [[ "$( uname )" == "Linux" ]];
then
    export PATH=$HOME/.local/bin:$PATH
    export PATH=$HOME/.linuxbrew/bin:$PATH
    export MANPATH=$HOME/.linuxbrew/share/man:$MANPATH
    export INFOPATH=$HOME/.linuxbrew/share/info:$INFOPATH
fi

# Aliases
source ~/.shell/aliases.sh

# Secrets file
source ~/.shell/secrets.sh

# External settings
source ~/.shell/external.sh

# OS-specific
if [[ "$( uname )" == "Darwin" ]];
then
    source ~/.shell/macOS.sh
fi
