export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.linuxbrew/bin:$PATH

# Aliases
source ~/.shell/aliases.sh

# Secrets file
source ~/.shell/secrets.sh

# External settings
source ~/.shell/external.sh

# OS-specific
if [[ "$(uname)" == "Darwin" ]];
then
    source ~/.shell/macOS.sh
fi
